config/routes.rb
Sheepdeveloper::Application.routes.draw do
  namespace :content do
    resources :pruebas
  end

  get "sliders/index"
  get "sliders/new"
  get "sliders/edit"
  get "sliders/view"
  get "admins/index"
  get "mains/index"

   root to: "mains#index"

  namespace :content do 
    
    get 'mains/index'
    resources :pages do
      collection do 
        get 'index'    
        get 'page_about'        
        get 'page_services'
        get 'page_pricing'
        get 'page_coming_soon'
        get 'page_faq'
        get 'page_search'
        get 'page_gallery'
        get 'page_registration'
        get 'page_login'
        get 'page_404'
        get 'page_clients'
        get 'page_privacy'
        get 'page_terms'
        get 'page_column_left'
        get 'page_column_right'
        get 'feature_grid'
        get 'feature_typography'
        get 'feature_thumbnail'
        get 'feature_component'
        get 'feature_navigation'
        get 'feature_table'
        get 'feature_form'
        get 'feature_icons'
        get 'feature_button'
        get 'portfolio'
        get 'portfolio_item'
        get 'portfolio_2columns'
        get 'portfolio_3columns'
        get 'portfolio_4columns'
        get 'blog'
        get 'blog_item'
        get 'blog_left_sidebar'
        get 'blog_item_left_sidebar'
        get 'page_contact'
        get 'page_contact1'  
      end
    end   
    resources :mains do
      collection do        
        get 'page_home2'
        get 'page_home3'
        get 'page_home4'
        get 'page_home5'
        get 'page_home6'
        get 'page_home7'
        get 'all_in_one'
      end  
    end
    resources :admins do
      collection do
        get 'index'
      end
    end
    resources :sliders do
      collection do
        get "index"
        get "new"
      end
    end
  end

end

app/models/content.rb
module Content
  def self.table_name_prefix
    'content_'
  end
end

app/models/content/prueba.rb
class Content::Prueba < ActiveRecord::Base
end

app/models/content/slider.rb
class Content::Slider < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/content/admins_controller.rb
class Content::AdminsController < ApplicationController

	layout "content/admin"
  def index
  end
end

app/controllers/content/mains_controller.rb
class Content::MainsController < ApplicationController

  layout "content/global"

  def index
  end

  def page_home2
  end

  def page_home3
  end

  def page_home4
  end

  def page_home5
  end

  def page_home6
  end

  def page_home7
  end

  def all_in_one
  end

end

app/controllers/content/pages_controller.rb
class Content::PagesController < ApplicationController
	
  def index
  end

  def page_about
  end

  def page_services
  end

  def page_pricing
  end

  def page_coming_soon
  end

  def page_faq
  end

  def page_search
  end

  def page_gallery
  end

  def page_registration
  end

  def page_login
  end

  def page_404
  end

  def page_clients
  end

  def page_privacy
  end

  def page_terms
  end

  def page_column_left
  end

  def page_column_right
  end

  def feature_grid
  end

  def feature_typography
  end

  def feature_thumbnail
  end

  def feature_component
  end

  def feature_navigation
  end

  def feature_table
  end

  def feature_form
  end

  def feature_icons
  end

  def feature_button
  end

  def portfolio
  end

  def portfolio_item
  end

  def portfolio_2columns
  end

  def portfolio_3columns
  end

  def portfolio_4columns
  end

  def blog
  end

  def blog_item
  end

  def blog_left_sidebar
  end

  def blog_item_left_sidebar
  end

  def page_contact
  end

  def page_contact1
  end

end

app/controllers/content/pruebas_controller.rb
class Content::PruebasController < ApplicationController
  before_action :set_content_prueba, only: [:show, :edit, :update, :destroy]

  # GET /content/pruebas
  # GET /content/pruebas.json
  def index
    @content_pruebas = Content::Prueba.all
  end

  # GET /content/pruebas/1
  # GET /content/pruebas/1.json
  def show
  end

  # GET /content/pruebas/new
  def new
    @content_prueba = Content::Prueba.new
  end

  # GET /content/pruebas/1/edit
  def edit
  end

  # POST /content/pruebas
  # POST /content/pruebas.json
  def create
    @content_prueba = Content::Prueba.new(content_prueba_params)

    respond_to do |format|
      if @content_prueba.save
        format.html { redirect_to @content_prueba, notice: 'Prueba was successfully created.' }
        format.json { render action: 'show', status: :created, location: @content_prueba }
      else
        format.html { render action: 'new' }
        format.json { render json: @content_prueba.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /content/pruebas/1
  # PATCH/PUT /content/pruebas/1.json
  def update
    respond_to do |format|
      if @content_prueba.update(content_prueba_params)
        format.html { redirect_to @content_prueba, notice: 'Prueba was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @content_prueba.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content/pruebas/1
  # DELETE /content/pruebas/1.json
  def destroy
    @content_prueba.destroy
    respond_to do |format|
      format.html { redirect_to content_pruebas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content_prueba
      @content_prueba = Content::Prueba.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_prueba_params
      params.require(:content_prueba).permit(:nombre, :apellidos)
    end
end

app/controllers/content/sliders_controller.rb
class Content::SlidersController < ApplicationController
  layout "content/admin"


  def index

  end

  def new
  		@slider = Content::Slider.new
  end

  def edit

  end

  def view

  end

  private
  def slider_parameters
    params.require(:slider).permit!
  end

end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  def index
  	redirect_to "/content/mains/"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content/admins_helper.rb
module Content::AdminsHelper
end

app/helpers/content/main_helper.rb
module Content::MainHelper
end

app/helpers/content/mains_helper.rb
module Content::MainsHelper
end

app/helpers/content/pages_helper.rb
module Content::PagesHelper
end

app/helpers/content/pruebas_helper.rb
module Content::PruebasHelper
end

app/helpers/content/sliders_helper.rb
module Content::SlidersHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/content/_footer.html.erb
<!--=== Footer ===-->
<div class="footer">
	<div class="container">
		<div class="row-fluid">
			<div class="span4">
                <!-- About -->
		        <div class="headline"><h3>About</h3></div>	
				<p class="margin-bottom-25">Unify is an incredibly beautiful responsive Bootstrap Template for corporate and creative professionals.</p>	

	            <!-- Monthly Newsletter -->
		        <div class="headline"><h3>Monthly Newsletter</h3></div>	
				<p>Subscribe to our newsletter and stay up to date with the latest news and deals!</p>
				<form class="form-inline" />
					<div class="input-append">
						<input type="text" placeholder="Email Address" class="input-medium" />
						<button class="btn-u">Subscribe</button>
					</div>
				</form>							
			</div><!--/span4-->	
			
			<div class="span4">
                <div class="posts">
                    <div class="headline"><h3>Recent Blog Entries</h3></div>
                    <dl class="dl-horizontal">
                        <dt><a href="#"><img src="/assets/content/sliders/elastislide/6.jpg" alt="" /></a></dt>
                        <dd>
                            <p><a href="#">Anim moon officia Unify is an incredibly beautiful responsive Bootstrap Template</a></p> 
                        </dd>
                    </dl>
                    <dl class="dl-horizontal">
                    <dt><a href="#"><img src="/assets/content/sliders/elastislide/10.jpg" alt="" /></a></dt>
                        <dd>
                            <p><a href="#">Anim moon officia Unify is an incredibly beautiful responsive Bootstrap Template</a></p> 
                        </dd>
                    </dl>
                    <dl class="dl-horizontal">
                    <dt><a href="#"><img src="/assets/content/sliders/elastislide/11.jpg" alt="" /></a></dt>
                        <dd>
                            <p><a href="#">Anim moon officia Unify is an incredibly beautiful responsive Bootstrap Template</a></p> 
                        </dd>
                    </dl>
                </div>
			</div><!--/span4-->

			<div class="span4">
	            <!-- Monthly Newsletter -->
		        <div class="headline"><h3>Contact Us</h3></div>	
                <address>
					25, Lorem Lis Street, Orange <br />
					California, US <br />
					Phone: 800 123 3456 <br />
					Fax: 800 123 3456 <br />
					Email: <a href="mailto:info@anybiz.com" class="">info@anybiz.com</a>
                </address>

                <!-- Stay Connected -->
		        <div class="headline"><h3>Stay Connected</h3></div>	
                <ul class="social-icons">
                    <li><a href="#" data-original-title="Feed" class="social_rss"></a></li>
                    <li><a href="#" data-original-title="Facebook" class="social_facebook"></a></li>
                    <li><a href="#" data-original-title="Twitter" class="social_twitter"></a></li>
                    <li><a href="#" data-original-title="Goole Plus" class="social_googleplus"></a></li>
                    <li><a href="#" data-original-title="Pinterest" class="social_pintrest"></a></li>
                    <li><a href="#" data-original-title="Linkedin" class="social_linkedin"></a></li>
                    <li><a href="#" data-original-title="Vimeo" class="social_vimeo"></a></li>
                </ul>
			</div><!--/span4-->
		</div><!--/row-fluid-->	
	</div><!--/container-->	
</div><!--/footer-->	
<!--=== End Footer ===-->

<!--=== Copyright ===-->
<div class="copyright">
	<div class="container">
		<div class="row-fluid">
			<div class="span8">						
	            <p>2013 &copy; Unify. ALL Rights Reserved. <a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a></p>
			</div>
			<div class="span4">	
				<a href="index.html"><img id="logo-footer" src="/assets/content/logo2-default.png" class="pull-right" alt="" /></a>
			</div>
		</div><!--/row-fluid-->
	</div><!--/container-->	
</div><!--/copyright-->	
<!--=== End Copyright ===-->

app/views/content/_head_top_info.html.erb
<!--=== Top ===-->    
<div class="top">
    <div class="container">                 
        <div class="row-fluid">
            <ul class="loginbar inline">
                <li><a href="mailto:info@anybiz.com"><i class="icon-envelope-alt"></i> info@anybiz.com</a></li> 
                <li><a><i class="icon-phone-sign"></i> 010 4202 2656</a></li>   
                <li><a href="page_login.html"><i class="icon-user"></i> LOGIN</a></li> 
            </ul>
        </div>                        
    </div><!--/container-->     
</div><!--/top-->
<!--=== End Top ===-->

app/views/content/_head_top_languaje.html.erb
<div class="top">
    <div class="container">         
        <ul class="loginbar pull-right">
            <li><i class="icon-globe"></i><a>Languages <i class="icon-sort-up"></i></a>
                <ul class="nav-list">
                    <li class="active"><a href="#">English</a> <i class="icon-ok"></i></li>
                    <li><a href="#">Spanish</a></li>
                    <li><a href="#">Russian</a></li>
                    <li><a href="#">German</a></li>
                </ul>
            </li>   
            <li class="devider">&nbsp;</li>
            <li><a href="page_faq.html" class="login-btn">Help</a></li>  
            <li class="devider">&nbsp;</li>
            <li><%= link_to "Admin", content_admins_path %></li>
            <li class="devider">&nbsp;</li>
            <li><a href="page_login.html" class="login-btn">Login</a></li>   
        </ul>
    </div>      
</div><!--/top-->

app/views/content/_menu.html.erb
        <!-- Menu -->       
        <div class="navbar">                                
            <div class="navbar-inner">                                  
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a><!-- /nav-collapse -->                                  
                <div class="nav-collapse collapse">                                     
                    <ul class="nav top-2">
                        <li class="active">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Home
                                <b class="caret"></b>                            
                            </a>
                            <ul class="dropdown-menu">
                                <li class="active"><%= link_to "Option1: Landing Page", content_mains_path %></li>
                                <li><%= link_to "Option2: Header Option", page_home2_content_mains_path %></li>
                                <li><%= link_to "Option3: Revolution Slider", page_home3_content_mains_path %></li>
                                <li><%= link_to "Option4: Amazing Content", page_home4_content_mains_path %></li>
                                <li><%= link_to "Option5: Mixed Content", page_home5_content_mains_path %></li>
                                <li><%= link_to "Option6: Content with Sidebar", page_home6_content_mains_path %></li>
                                <li><%= link_to "Option7: Aplle Style Slider", page_home7_content_mains_path %></li>
                                <li><%= link_to "Home All In One", all_in_one_content_mains_path %></li>
                            </ul>
                            <b class="caret-out"></b>                        
                        </li>
                        <li>
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">Paginas
                                <b class="caret"></b>                            
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "About Us", page_about_content_pages_path %></li>
                                <li><%= link_to "page_services", page_services_content_pages_path %></li>
                                <li><%= link_to "page_pricing", page_pricing_content_pages_path %></li>
                                <li><%= link_to "page_coming_soon", page_coming_soon_content_pages_path %></li>
                                <li><%= link_to "FAQs", page_faq_content_pages_path %></li>
                                <li><%= link_to "Search Result", page_search_content_pages_path %></li>
                                <li><%= link_to "Gallery", page_gallery_content_pages_path %></li>
                                <li><%= link_to "Registration", page_registration_content_pages_path %></li>
                                <li><%= link_to "Login", page_login_content_pages_path %></li>
                                <li><%= link_to "404", page_404_content_pages_path %></li>
                                <li><%= link_to "Clients", page_clients_content_pages_path %></li>
                                <li><%= link_to "Privacy Policy", page_privacy_content_pages_path %></li>
                                <li><%= link_to "Terms of Service", page_terms_content_pages_path %></li>
                                <li><%= link_to "2 Columns (Left)", page_column_left_content_pages_path %></li>
                                <li><%= link_to "2 Columns (Right)", page_column_right_content_pages_path %></li>
                            </ul>
                            <b class="caret-out"></b>                        
                        </li>
                        <li>
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">Features
                                <b class="caret"></b>                            
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Grid Layout", feature_grid_content_pages_path %></li>
                                <li><%= link_to "Typography", feature_typography_content_pages_path %></li>
                                <li><%= link_to "Thumbnails", feature_thumbnail_content_pages_path %></li>
                                <li><%= link_to "Components", feature_component_content_pages_path %></li>
                                <li><%= link_to "Navigation", feature_navigation_content_pages_path %></li>
                                <li><%= link_to "Tables", feature_table_content_pages_path %></li>
                                <li><%= link_to "Forms", feature_form_content_pages_path %></li>
                                <li><%= link_to "Icons", feature_icons_content_pages_path %></li>
                                <li><%= link_to "Buttons", feature_button_content_pages_path %></li>
                            </ul>
                            <b class="caret-out"></b>                        
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio
                                <b class="caret"></b>                            
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Portfolio", portfolio_content_pages_path %></li>
                                <li><%= link_to "Portfolio Item", portfolio_item_content_pages_path %></li>
                                <li><%= link_to "Portfolio 2 Columns", portfolio_2columns_content_pages_path %></li>
                                <li><%= link_to "Portfolio 3 Columns", portfolio_3columns_content_pages_path %></li>
                                <li><%= link_to "Portfolio 4 Columns", portfolio_4columns_content_pages_path %></li>
                            </ul>
                            <b class="caret-out"></b>                        
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog
                                <b class="caret"></b>                            
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Blog", blog_content_pages_path %></li>
                                <li><%= link_to "Blog Item", blog_item_content_pages_path %></li>
                                <li><%= link_to "Blog Left Sidebar", blog_left_sidebar_content_pages_path %></li>
                                <li><%= link_to "Blog Item Left Sidebar", blog_item_left_sidebar_content_pages_path %></li>
                            </ul>
                            <b class="caret-out"></b>                        
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contact
                                <b class="caret"></b>                            
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Contact Default", page_contact_content_pages_path %></li>
                                <li><%= link_to "Contact Boxed Map", page_contact1_content_pages_path %></li>
                            </ul>
                            <b class="caret-out"></b>                        
                        </li>
                        <li><a class="search"><i class="icon-search search-btn"></i></a></li>                               
                    </ul>
                    <div class="search-open">
                        <div class="input-append">
                            <form />
                                <input type="text" class="span3" placeholder="Search" />
                                <button type="submit" class="btn-u">Go</button>
                            </form>
                        </div>
                    </div>
                </div><!-- /nav-collapse -->                                
            </div><!-- /navbar-inner -->
        </div><!-- /navbar -->  

app/views/content/admins/index.html.erb
<h1>Content::Admins#index</h1>
<p>Find me in app/views/content/admins/index.html.erb</p>

app/views/content/pages/index.html.erb
<h1>Content::Pages#index</h1>
<p>Find me in app/views/content/pages/index.html.erb</p>

app/views/content/pages/page_404.html.erb


<% content_for :js_plugin do %>
    <link rel="stylesheet" href="/assets/content/plugins/font-awesome/css/font-awesome.css" />
<% end %>



<!--=== Breadcrumbs ===-->
<div class="breadcrumbs margin-bottom-40">
	<div class="container">
        <h1 class="color-green pull-left">Page Not Founded</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a> <span class="divider">/</span></li>
            <li><a href="">Pages</a> <span class="divider">/</span></li>
            <li class="active">404</li>
        </ul>
    </div><!--/container-->
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Content Part ===-->
<div class="container">		
	<div class="row-fluid page-404">
    	<p><i>404</i> <span>The Page cannot be found</span></p>
    </div><!--/row-fluid-->        
</div><!--/container-->		
<!--=== End Content Part ===-->
 
<!-- JS Plugins -->     
<% content_for :js_plugin do %> 
<link rel="stylesheet" href="/assets/content/plugins/font-awesome/css/font-awesome.css" />
<% end %>     
        

<!-- JS Inicializer -->
<% content_for :js_inicializer do %>
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init();
    });
</script>
<%end%>

app/views/content/pruebas/_form.html.erb
<%= form_for(@content_prueba) do |f| %>
  <% if @content_prueba.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content_prueba.errors.count, "error") %> prohibited this content_prueba from being saved:</h2>

      <ul>
      <% @content_prueba.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellidos %><br>
    <%= f.text_field :apellidos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/content/pruebas/edit.html.erb
<h1>Editing content_prueba</h1>

<%= render 'form' %>

<%= link_to 'Show', @content_prueba %> |
<%= link_to 'Back', content_pruebas_path %>

app/views/content/pruebas/index.html.erb
<h1>Listing content_pruebas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @content_pruebas.each do |content_prueba| %>
      <tr>
        <td><%= content_prueba.nombre %></td>
        <td><%= content_prueba.apellidos %></td>
        <td><%= link_to 'Show', content_prueba %></td>
        <td><%= link_to 'Edit', edit_content_prueba_path(content_prueba) %></td>
        <td><%= link_to 'Destroy', content_prueba, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prueba', new_content_prueba_path %>

app/views/content/pruebas/new.html.erb
<h1>New content_prueba</h1>

<%= render 'form' %>

<%= link_to 'Back', content_pruebas_path %>

app/views/content/pruebas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @content_prueba.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @content_prueba.apellidos %>
</p>

<%= link_to 'Edit', edit_content_prueba_path(@content_prueba) %> |
<%= link_to 'Back', content_pruebas_path %>

app/views/content/sliders/_form.html.erb
<%= form_for(@slider, :html => {:class => "form-horizontal"}) do |f| %>
	<div class="control-group">
		<div class="control-label">
			<%= f.label :titulo_primero %>
		</div>
		<div class="controls">
			<%= f.text_field :title_one %>
		</div>
	</div>
<% end %>

app/views/content/sliders/edit.html.erb
<h1>Content::Sliders#edit</h1>
<p>Find me in app/views/content/sliders/edit.html.erb</p>

app/views/content/sliders/index.html.erb
<div class="page-header">
	<h1>Lista de Sliders</h1>
</div>
<div class="row">
	<table class="table table-bordered table-hover">
		<tr class="well">
			<th>Id</th>
			<th>Resumen</th>
			<th>Activo</th>			
			<th>Acciones</th>
		</tr>
	</table>
</div>
<div class="form-actions">
	<%= link_to raw("<i class='icon-home icon-white'></i> Nuevo"), new_content_slider_path, class: "btn btn-primary" %>
</div>

app/views/content/sliders/new.html.erb
<div class="page-header">
	<h1>Nuevo Item Slider</h1>
</div>

<%= render 'form' %>

app/views/content/sliders/view.html.erb
<h1>Content::Sliders#view</h1>
<p>Find me in app/views/content/sliders/view.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sheepdeveloper</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/content/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Admin</title>

    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag  "/assets/content/bootstrap_admin.css" %>  	

    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">
    <style type="text/css">
    body {
		  padding-top: 50px;
		}
		.starter-template {
		  padding: 40px 15px;
		  text-align: center;
		}
    </style>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Admin", content_admins_path, :class => 'navbar-brand' %>          
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Slider", content_sliders_path %></li>
            <li><a href="#about">Blog</a></li>
            <li><a href="#contact">Paginas</a></li>
            <li><a href="#contact">Portafolio</a></li>
            <li><a href="#contact">Team</a></li>
            <li><a href="#contact">Faq</a></li>
            <li><a href="#contact">Frases</a></li>
            <li><a href="#contact">Comentarios</a></li>            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <%= yield %>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>





app/views/layouts/content/mains.html.erb
<%= yield %>

app/views/mains/index.html.erb
<h1>Mains#index</h1>
<p>Find me in app/views/mains/index.html.erb</p>